name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    
    # --- THIS IS THE FIX ---
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # -----------------------
      
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install "jupyter-book<=0.15.1"

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
